name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    # - name: Restore dependencies
    #   run: dotnet restore
    - name: Build
      run: dotnet build 
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
    - name: Push to NuGet
      run: dotnet nuget push "/home/runner/work/Reusable.Methods.NET/Reusable.Methods.NET/Reusable.Methods.NET/bin/Debug/*.nupkg" ${{secrets.nuget_api_key}} 
